export const commands = {
    "console": "konsol",
    "log": "skriv",
    "function": "funktion",
    "let": "låt",
    "const": "konstant",
    "class": "klass",
    "return": "returnera",
    "constructor": "konstruktor",
    "this": "denna",
    "require": "kräv",
    "export": "exportera",
    "exports": "exporteras",
    "module": "modul",
    "push": "putta",
    "split": "splitta",
    "slice": "skär",
    "find": "hitta",
    "map":"karta",
    "join":"sammansätt",
    "keys":"nycklar",
    "pop":"spräng",
    "length":"längd",
    "sort":"sortera",
    "toString": "tillString",
    "includes": "inkluderar",
    "forEach": "förVarje",
    "findIndex": "hittaPlats",
    "isArray": "ärLista",
    "filter": "filtrera",
    "concat": "sammansätt",
    "static":"statisk",
    "extends":"förlänger",
    "try":"försök",
    "catch":"fånga",
    "parse":"tolka",
    "stringify":"stringifiera",
    "trim":"klipp",
    "search":"leta",
    "replace":"ersätt",
    "toLowerCase":"tillGemen",
    "toUpperCase":"tillVersal",
    "startsWith":"startarMed",
    "endsWith":"slutarMed",
    "repeat":"repetera",
    "indexOf":"platsAv",
    "break":"bryt",
    "continue":"fortsätt",
    "do":"gör",
    "for":"för",
    "in":"i",
    "of":"av",
    "switch":"byta",
    "throw":"kasta",
    "finally":"äntligen",
    "var":"variabel",
    "while":"medan",
    "else":"annars",
    "if":"om",
    "new": "ny",
    "typeof":"typav",
    "case":"fall",
    "async":"asynkron",
    "await":"vänta"
}